image: "node:lts-alpine"

stages:
- build
- deploy

build_app:
  stage: build
  script:
  - npm install libtool automake autoconf nasm libpng pkg-config
  - yarn install
  - yarn build
  artifacts:
    paths:
    - build
    expire_in: 1 day

deploy_draft:
  stage: deploy
  only:
  - master
  script:
  - npm install -g netlify-cli
  - netlify deploy --site ${NETLIFY_SITE_ID} --auth ${NETLIFY_TOKEN} --dir build

deploy_prod:
  stage: deploy
  only:
  - master
  script:
  - npm install -g netlify-cli
  - netlify deploy --site ${NETLIFY_SITE_ID} --auth ${NETLIFY_TOKEN} --dir build --prod
  when: manual