image: "node:latest"

stages:
- build
- deploy

build_app:
  stage: build
  script:
  - yarn install
  - npm run build
  artifacts:
    paths:
    - build
    expire_in: 1 day

deploy_draft:
  stage: deploy
  only:
  - master
  script:
  - npm install -g netlify-cli
  - netlify deploy --site ${NETLIFY_SITE_ID} --auth ${NETLIFY_TOKEN} --dir public

deploy_prod:
  stage: deploy
  only:
  - master
  script:
  - npm install -g netlify-cli
  - netlify deploy --site ${NETLIFY_SITE_ID} --auth ${NETLIFY_TOKEN} --dir public --prod
  when: manual